x1, y1 = map(int, input().split())
x2, y2 = map(int, input().split())
x3, y3 = map(int, input().split())
minx, maxx = min(x1, x2, x3), max(x1, x2, x3)
miny, maxy = min(y1, y2, y3), max(y1, y2, y3)
pts = set([(minx, miny), (minx, maxy), (maxx, miny), (maxx, maxy)])
cur = set([(x1, y1), (x2, y2), (x3, y3)])
print(' '.join(map(str, (pts - cur).pop())))